# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [11]:
# Import torch
import torch

# Create random tensor
tensor7x7 = torch.rand(7, 7)
tensor7x7

tensor([[0.2789, 0.8183, 0.7996, 0.5568, 0.2447, 0.2949, 0.0856],
        [0.1773, 0.2660, 0.2323, 0.0889, 0.2448, 0.1249, 0.7439],
        [0.0272, 0.8719, 0.5615, 0.3730, 0.5262, 0.0851, 0.4918],
        [0.5508, 0.5733, 0.5311, 0.6802, 0.7974, 0.7291, 0.4145],
        [0.9793, 0.0391, 0.0161, 0.1601, 0.3989, 0.7635, 0.9259],
        [0.6304, 0.3369, 0.8382, 0.6855, 0.8176, 0.1728, 0.1727],
        [0.7298, 0.1030, 0.8455, 0.1036, 0.0802, 0.5939, 0.4265]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
tensor1x7 = torch.rand(1, 7)

# Perform matrix multiplication 
result1 = torch.matmul(tensor1x7, tensor7x7) #shape (1, 7)
result2 = tensor7x7 @ tensor1x7.T #shape (7, 1)
tensor1x7, result1, result2

(tensor([[0.5295, 0.6186, 0.4603, 0.8079, 0.9047, 0.5088, 0.0338]]),
 tensor([[1.9463, 1.6726, 1.7242, 1.5683, 1.9470, 1.6604, 2.0067]]),
 tensor([[1.8461],
         [0.7473],
         [1.6496],
         [2.5468],
         [1.4601],
         [2.3153],
         [1.3122]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor2 = torch.rand(7, 7)
tensor3 = torch.rand(1, 7)

# Matrix multiply tensors
prod = torch.matmul(tensor2, tensor3.T)

torch.random.manual_seed(0)
tensor2_copy = torch.rand(7, 7)

# Check if tensors are equal
if torch.equal(tensor2, tensor2_copy):
    print("Tensors are equal")
else:
    print("Tensors are not equal")

prod

Tensors are equal


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [39]:
# Set random seed on the GPU
# torch.cuda.manual_seed(0)
# tensor2 = torch.rand(7, 7)
# tensor2 = tensor2.to(device='cuda:0')
#
# tensor3 = torch.rand(1, 7)
# tensor3 = tensor3.to(device='cuda:0')

device = torch.device("cuda:0")

torch.cuda.manual_seed(1234)


device1 = torch.device("cuda:1")
tensor2 = torch.rand(7, 7, device=device)
tensor3 = torch.rand(1, 7, device=device1)
prod = torch.matmul(tensor2, tensor3.to(device).T)
prod

tensor([[1.8615],
        [1.8355],
        [1.3925],
        [2.5659],
        [1.4376],
        [0.9729],
        [1.3753]], device='cuda:0')


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [28]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
print('torch.cuda.is_available', torch.cuda.is_available(), torch.__version__)        # True

# Create two random tensors on GPU
tensor2 = torch.rand(7, 7, device=device)
tensor3 = torch.rand(1, 7, device=device)

tensor2, tensor3


torch.cuda.is_available True 2.2.2
torch.Size([7, 1]) cuda:0


(tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
         [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
         [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
         [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
         [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
         [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
         [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
        device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255, 0.1114, 0.6812, 0.3608, 0.1715]],
        device='cuda:0'),
 tensor([[0.9558],
         [1.2227],
         [0.9335],
         [1.6030],
         [0.9344],
         [0.5282],
         [0.5664]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [29]:
# Perform matmul on tensor_A and tensor_B
prod = torch.matmul(tensor2, tensor3.T)
print(prod.shape, prod.device)

prod

torch.Size([7, 1]) cuda:0


tensor([[0.9558],
        [1.2227],
        [0.9335],
        [1.6030],
        [0.9344],
        [0.5282],
        [0.5664]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [31]:
# Find max
max = prod.max()
min = prod.min()
min, max
# Find min


(tensor(0.5282, device='cuda:0'), tensor(1.6030, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
min_idx = torch.argmin(prod)
max_idx = torch.argmax(prod)
min_idx, max_idx
# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [42]:
# Set seed
torch.cuda.manual_seed(1)

# Create random tensor
tensor10 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor10_squeezed = tensor10.squeeze()
# Print out tensors and their shapes
print(tensor10, tensor10.shape)
print(tensor10_squeezed, tensor10_squeezed.shape)

tensor([[[[0.4897, 0.3875, 0.1918, 0.8458, 0.1278, 0.7048, 0.3319, 0.2588,
           0.5898, 0.2403]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4897, 0.3875, 0.1918, 0.8458, 0.1278, 0.7048, 0.3319, 0.2588, 0.5898,
        0.2403]) torch.Size([10])
