In [2]:
# import random
import torch

print('torch.cuda.is_available', torch.cuda.is_available(), torch.__version__)        # True
print('torch.cuda.device_count', torch.cuda.device_count())        # 2
print('torch.cuda.get_device_name', torch.cuda.get_device_name(0)) # 3090 ti




torch.cuda.is_available True 2.2.2
torch.cuda.device_count 2
torch.cuda.get_device_name NVIDIA GeForce RTX 3090 Ti


In [4]:

x = torch.rand(5, 3)
# print(x, torch.__version__)
torch.set_default_dtype(torch.float64)

tensor_arr = torch.Tensor([[5, 3], [4, 3]]).type(torch.IntTensor)

print(torch.is_tensor(tensor_arr), tensor_arr, torch.numel(tensor_arr))

uninitialized = torch.Tensor(3, 5).type(torch.int64)
print(uninitialized)

# Define indices and values for a 3x3 sparse tensor
indices = torch.tensor([[0, 1, 2],
                        [1, 2, 2]], dtype=torch.int64) # Non-zero elements at (0,0), (1,1), (2,2)
values = torch.tensor([1.0, 2.0, 3.0])

# Construct the sparse COO tensor
sparse_tensor = torch.sparse_coo_tensor(indices, values, size=(3, 3))

print(sparse_tensor)
print(sparse_tensor.to_dense()) # Convert to dense for visualization

True tensor([[5, 3],
        [4, 3]], dtype=torch.int32) 4
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])
tensor(indices=tensor([[0, 1, 2],
                       [1, 2, 2]]),
       values=tensor([1., 2., 3.]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)
tensor([[0., 1., 0.],
        [0., 0., 2.],
        [0., 0., 3.]])


In [6]:
%%time
tensor = torch.tensor([1, 2, 3])
tt = tensor * tensor
print('tensor * tensor', tt, 'ndim', tt.ndim, 'shape', tt.shape)

matmul = tensor.matmul(tensor)
print('tensor.matmul(tensor)', matmul, 'ndim', matmul.ndim, 'shape', matmul.shape)

matmul_at = tensor @ tensor
print('tensor @ tensor', matmul_at, 'ndim', matmul_at.ndim, 'shape', matmul_at.shape)




tensor * tensor tensor([1, 4, 9]) ndim 1 shape torch.Size([3])
tensor.matmul(tensor) tensor(14) ndim 0 shape torch.Size([])
tensor @ tensor tensor(14) ndim 0 shape torch.Size([])
CPU times: user 136 ms, sys: 0 ns, total: 136 ms
Wall time: 138 ms


In [7]:
# Scalar
scalar = torch.tensor(7)
print('scalar', scalar, 'ndim', scalar.ndim, 'item', scalar.item())

# Vector
vector = torch.tensor([7, 7])
print('vector', vector, 'ndim', vector.ndim, 'shape', vector.shape)

# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print('MATRIX', MATRIX, 'ndim', MATRIX.ndim, 'shape', MATRIX.shape)

# MATRIX
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print('TENSOR', TENSOR, 'ndim', TENSOR.ndim, 'shape', TENSOR.shape)

scalar tensor(7) ndim 0 item 7
vector tensor([7, 7]) ndim 1 shape torch.Size([2])
MATRIX tensor([[ 7,  8],
        [ 9, 10]]) ndim 2 shape torch.Size([2, 2])
TENSOR tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]]) ndim 3 shape torch.Size([1, 3, 3])


In [13]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.mm(tensor_A.T, tensor_B)


tensor([[ 76., 103.],
        [100., 136.]], dtype=torch.float32)

In [14]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]], dtype=torch.float32)

In [18]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6],
                  [7, 8]], dtype=torch.double)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")
print("Weights", linear.weight.shape)  # Output: torch.Size([6, 2])
print("Bias shape", linear.bias.shape)    # Output: torch.Size([6])

Input shape: torch.Size([4, 2])

Output:
tensor([[-1.3767, -1.2739, -0.2018,  2.0155, -2.2105, -0.5530],
        [-3.8627, -3.6040, -0.1935,  4.5158, -4.4275, -1.8755],
        [-6.3488, -5.9342, -0.1851,  7.0161, -6.6444, -3.1980],
        [-8.8348, -8.2643, -0.1768,  9.5164, -8.8614, -4.5205]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([4, 6])
Weights torch.Size([6, 2])
Bias shape torch.Size([6])


In [26]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


(tensor(90), tensor(0), tensor(45., dtype=torch.float32), tensor(450))

In [25]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [65]:
x = torch.arange(0.8, 8.7)

x_reshaped = x.reshape(8, 1)
x_reshaped, x_reshaped.shape

(tensor([[0.8000],
         [1.8000],
         [2.8000],
         [3.8000],
         [4.8000],
         [5.8000],
         [6.8000],
         [7.8000]]),
 torch.Size([8, 1]))

In [66]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x_reshaped.view(1, 8)
# x_reshaped[:, 0] = 9
z, z.shape, x, x_reshaped

(tensor([[0.8000, 1.8000, 2.8000, 3.8000, 4.8000, 5.8000, 6.8000, 7.8000]]),
 torch.Size([1, 8]),
 tensor([0.8000, 1.8000, 2.8000, 3.8000, 4.8000, 5.8000, 6.8000, 7.8000]),
 tensor([[0.8000],
         [1.8000],
         [2.8000],
         [3.8000],
         [4.8000],
         [5.8000],
         [6.8000],
         [7.8000]]))

In [67]:
x_stacked = torch.stack([x_reshaped, x_reshaped, x_reshaped, x_reshaped], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[[0.8000],
         [1.8000],
         [2.8000],
         [3.8000],
         [4.8000],
         [5.8000],
         [6.8000],
         [7.8000]],

        [[0.8000],
         [1.8000],
         [2.8000],
         [3.8000],
         [4.8000],
         [5.8000],
         [6.8000],
         [7.8000]],

        [[0.8000],
         [1.8000],
         [2.8000],
         [3.8000],
         [4.8000],
         [5.8000],
         [6.8000],
         [7.8000]],

        [[0.8000],
         [1.8000],
         [2.8000],
         [3.8000],
         [4.8000],
         [5.8000],
         [6.8000],
         [7.8000]]])

In [76]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[0.8000],
        [1.8000],
        [2.8000],
        [3.8000],
        [4.8000],
        [5.8000],
        [6.8000],
        [7.8000]])
Previous shape: torch.Size([8, 1])

New tensor: tensor([0.8000, 1.8000, 2.8000, 3.8000, 4.8000, 5.8000, 6.8000, 7.8000])
New shape: torch.Size([8])


In [75]:
t = x_reshaped.view(1, 8, 1)

print(f"Previous T tensor: {t}")
print(f"Previous T shape: {t.shape}")

# Remove extra dimension from x_reshaped
t_squeezed = t.squeeze(dim=2)
print(f"\nNew T tensor: {t_squeezed}")
print(f"New T shape: {t_squeezed.shape}")

Previous T tensor: tensor([[[0.8000],
         [1.8000],
         [2.8000],
         [3.8000],
         [4.8000],
         [5.8000],
         [6.8000],
         [7.8000]]])
Previous T shape: torch.Size([1, 8, 1])

New T tensor: tensor([[0.8000, 1.8000, 2.8000, 3.8000, 4.8000, 5.8000, 6.8000, 7.8000]])
New T shape: torch.Size([1, 8])


In [86]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(1).unsqueeze(2)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([0.8000, 1.8000, 2.8000, 3.8000, 4.8000, 5.8000, 6.8000, 7.8000])
Previous shape: torch.Size([8])

New tensor: tensor([[[0.8000]],

        [[1.8000]],

        [[2.8000]],

        [[3.8000]],

        [[4.8000]],

        [[5.8000]],

        [[6.8000]],

        [[7.8000]]])
New shape: torch.Size([8, 1, 1])


In [95]:
# Create tensor with specific shape
x_original = torch.rand(size=(2, 3, 4))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
                                        # shape: (4, 2, 3)

print(f"Previous shape: {x_original} {x_original.shape}")
print(f"New shape:  {x_permuted} {x_permuted.shape}")

Previous shape: tensor([[[0.4012, 0.5336, 0.9638, 0.2657],
         [0.2063, 0.2520, 0.3466, 0.8334],
         [0.1596, 0.4831, 0.8069, 0.5007]],

        [[0.5947, 0.4219, 0.2483, 0.3098],
         [0.1724, 0.7580, 0.4485, 0.1700],
         [0.2800, 0.4191, 0.9986, 0.5068]]]) torch.Size([2, 3, 4])
New shape:  tensor([[[0.4012, 0.2063, 0.1596],
         [0.5947, 0.1724, 0.2800]],

        [[0.5336, 0.2520, 0.4831],
         [0.4219, 0.7580, 0.4191]],

        [[0.9638, 0.3466, 0.8069],
         [0.2483, 0.4485, 0.9986]],

        [[0.2657, 0.8334, 0.5007],
         [0.3098, 0.1700, 0.5068]]]) torch.Size([4, 2, 3])


In [100]:
x = torch.arange(1, 10).reshape(1, 3, 3)
# Let's index bracket by bracket
print(f"First square bracket:\n{x}")
print(f"Second square bracket: {x[0][1]}")
print(f"Third square bracket: {x[0][1][0]}")
print(f"First Column: {x[:, 0]}")
print(f"Four4 square bracket: {x[0][1][1]}")


First square bracket:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Second square bracket: tensor([4, 5, 6])
Third square bracket: 4
First Column: tensor([[1, 2, 3]])
Third square bracket: 5


In [101]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.0582, 0.0629, 0.1236, 0.0526],
        [0.5262, 0.4768, 0.9552, 0.9288],
        [0.0835, 0.1326, 0.1571, 0.3754]])

Tensor D:
tensor([[0.0582, 0.0629, 0.1236, 0.0526],
        [0.5262, 0.4768, 0.9552, 0.9288],
        [0.0835, 0.1326, 0.1571, 0.3754]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])